name: Prepare next release

on:
  push:
    branches:
    - master

permissions:
  contents: write
  pull-requests: read

jobs:
  release-draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run release drafter
      uses: release-drafter/release-drafter@v7
      env:
        GITHUB_TOKEN: ${{ github.token }}
