name: Release

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect Go version
      id: vars
      run: echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ github.token }}
